stages:
- terraform_setup
- terraform_plan
- terraform_apply
- terraform_output
- docker_pull_push
- terraform_destroy

variables:
  AWS_REGION: "us-gov-west-1"
  DOTNET_IMAGE: "mcr.microsoft.com/dotnet/samples:aspnetapp"

terraform_setup:
  stage: terraform_setup
  image:
    name: hashicorp/terraform:latest
    entrypoint: [ "" ]
  script:
  - echo "Initializing Terraform without remote backend..."
  - aws sts get-caller-identity
  - terraform init
  - echo "Terraform setup complete."
  artifacts:
    paths:
    - .terraform
    - .terraform.lock.hcl
    - terraform.tfstate
    expire_in: 2 hours

terraform_plan:
  stage: terraform_plan
  image:
    name: hashicorp/terraform:latest
    entrypoint: [ "" ]
  dependencies:
    - terraform_setup
  script:
  - echo "Validating Terraform configuration..."
  - aws sts get-caller-identity
  - terraform validate
  - terraform plan -out=tfplan
  artifacts:
    paths:
    - tfplan
    - .terraform
    - .terraform.lock.hcl
    - terraform.tfstate
    expire_in: 2 hours

terraform_apply:
  stage: terraform_apply
  when: manual
  image:
    name: hashicorp/terraform:latest
    entrypoint: [ "" ]
  dependencies:
    - terraform_plan
  script:
  - echo "Reusing lock file and plan..."
  - aws sts get-caller-identity
  - terraform init
  - terraform apply -auto-approve tfplan
  artifacts:
    paths:
    - terraform.tfstate
    expire_in: 2 hours

terraform_output:
  stage: terraform_output
  needs: [ "terraform_apply" ]
  image:
    name: hashicorp/terraform:latest
    entrypoint: [ "" ]
  dependencies:
    - terraform_apply
  before_script:
  - apk add --no-cache jq
  script:
  - echo "Fetching Terraform outputs..."
  - aws sts get-caller-identity
  - terraform output -json > outputs.json
  - jq -r '.repository_url.value' outputs.json > repository_url
  - jq -r '.ecr_repository_name.value' outputs.json > ecr_repository_name
  artifacts:
    paths:
    - outputs.json
    - repository_url
    - ecr_repository_name
    expire_in: 2 hours

docker_pull_push:
  stage: docker_pull_push
  needs: [ "terraform_output" ]
  image:
    name: docker:latest
  services:
  - docker:dind
  before_script:
  - apk add --no-cache curl jq python3 py3-pip py3-virtualenv
  - python3 -m venv /tmp/venv
  - source /tmp/venv/bin/activate
  - pip install awscli
  - echo "Reading Terraform outputs from artifacts..."
  - export REPOSITORY_URL=$(cat repository_url)
  - export ECR_REPOSITORY_NAME=$(cat ecr_repository_name)
  - echo "Logging in to AWS ECR..."
  - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$REPOSITORY_URL"
  script:
  - echo "Pulling .NET sample image from Microsoft's registry..."
  - docker pull "$DOTNET_IMAGE"
  - echo "Tagging the image for ECR..."
  - docker tag "$DOTNET_IMAGE" "${REPOSITORY_URL}:latest"
  - echo "Pushing the image to ECR..."
  - docker push "${REPOSITORY_URL}:latest"

terraform_destroy:
  stage: terraform_destroy
  when: manual
  image:
    name: hashicorp/terraform:latest
    entrypoint: [ "" ]
  dependencies:
    - terraform_apply
  script:
  - echo "Destroying Terraform-managed infrastructure..."
  - aws sts get-caller-identity
  - terraform destroy -auto-approve
